apiVersion: apps/v1
kind: Deployment
metadata:
  name: vertex-deploy
  labels:
    app: myvertexapp
spec: 
  replicas: 3
  selector:
     matchLabels:
      app: myvertexapp
  template:
    metadata: 
      labels:  
         app: myvertexapp
    spec:
      containers:
        - name: deployment-container
          image: gouriboga/myvertexjava9dec22:1
          ports:
          - containerPort: 8080