apiVersion: v1
kind: ReplicationController
metadata:
  name: myvertex-rc
spec:
  replicas: 3
  selector:
    app: myvertexapp
  template:
    metadata:
      name: complexpod
      labels:
        app: myvertexapp
    spec:
      containers:
        - name: mynginx-container
          image: gouriboga/myvertexjava9dec22:1
          ports:
            - containerPort: 8080

